
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// import { headers } from "next/headers";

// import { SidebarProvider } from "@/components/ui/sidebar";
// import { PageSidebar } from "@/modules/page/ui/components/page-sidebar";
// import { PageNavbar } from "@/modules/page/ui/components/page-navbar";
// import { Providers } from "../providers";
// import { auth } from "../lib/auth";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const session = await auth.api.getSession({
//     headers: await headers(),
//   });

//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${inter.className} antialiased`}>
//         <Providers>
//           {!session?.user ? (
//             children
//           ) : (
//             <SidebarProvider>
//               <PageSidebar />
//               <main className="flex flex-col h-screen w-[90%] bg-muted">
//                 <PageNavbar />
//                 {children}
//               </main>
//             </SidebarProvider>
//           )}
//         </Providers>
//       </body>
//     </html>
//   );
// }
const Layout = ({children}: {children: React.ReactNode}) => {
  return (
    <main>
      {children}
    </main>
  )
};

export default Layout;

